/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: fmessage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "fmessage.pb-c.h"
void   submessage__init
                     (Submessage         *message)
{
  static const Submessage init_value = SUBMESSAGE__INIT;
  *message = init_value;
}
size_t submessage__get_packed_size
                     (const Submessage *message)
{
  assert(message->base.descriptor == &submessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t submessage__pack
                     (const Submessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &submessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t submessage__pack_to_buffer
                     (const Submessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &submessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Submessage *
       submessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Submessage *)
     protobuf_c_message_unpack (&submessage__descriptor,
                                allocator, len, data);
}
void   submessage__free_unpacked
                     (Submessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &submessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fmessage__init
                     (FMessage         *message)
{
  static const FMessage init_value = FMESSAGE__INIT;
  *message = init_value;
}
size_t fmessage__get_packed_size
                     (const FMessage *message)
{
  assert(message->base.descriptor == &fmessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fmessage__pack
                     (const FMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fmessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fmessage__pack_to_buffer
                     (const FMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fmessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FMessage *
       fmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FMessage *)
     protobuf_c_message_unpack (&fmessage__descriptor,
                                allocator, len, data);
}
void   fmessage__free_unpacked
                     (FMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fmessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor submessage__field_descriptors[1] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Submessage, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned submessage__field_indices_by_name[] = {
  0,   /* field[0] = value */
};
static const ProtobufCIntRange submessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor submessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Submessage",
  "Submessage",
  "Submessage",
  "",
  sizeof(Submessage),
  1,
  submessage__field_descriptors,
  submessage__field_indices_by_name,
  1,  submessage__number_ranges,
  (ProtobufCMessageInit) submessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fmessage__field_descriptors[1] =
{
  {
    "a",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(FMessage, n_a),
    offsetof(FMessage, a),
    &submessage__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fmessage__field_indices_by_name[] = {
  0,   /* field[0] = a */
};
static const ProtobufCIntRange fmessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor fmessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FMessage",
  "FMessage",
  "FMessage",
  "",
  sizeof(FMessage),
  1,
  fmessage__field_descriptors,
  fmessage__field_indices_by_name,
  1,  fmessage__number_ranges,
  (ProtobufCMessageInit) fmessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
