/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: fmessage.proto */

#ifndef PROTOBUF_C_fmessage_2eproto__INCLUDED
#define PROTOBUF_C_fmessage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Submessage Submessage;
typedef struct _FMessage FMessage;


/* --- enums --- */


/* --- messages --- */

struct  _Submessage
{
  ProtobufCMessage base;
  int32_t value;
};
#define SUBMESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&submessage__descriptor) \
    , 0 }


struct  _FMessage
{
  ProtobufCMessage base;
  size_t n_a;
  Submessage **a;
};
#define FMESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fmessage__descriptor) \
    , 0,NULL }


/* Submessage methods */
void   submessage__init
                     (Submessage         *message);
size_t submessage__get_packed_size
                     (const Submessage   *message);
size_t submessage__pack
                     (const Submessage   *message,
                      uint8_t             *out);
size_t submessage__pack_to_buffer
                     (const Submessage   *message,
                      ProtobufCBuffer     *buffer);
Submessage *
       submessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   submessage__free_unpacked
                     (Submessage *message,
                      ProtobufCAllocator *allocator);
/* FMessage methods */
void   fmessage__init
                     (FMessage         *message);
size_t fmessage__get_packed_size
                     (const FMessage   *message);
size_t fmessage__pack
                     (const FMessage   *message,
                      uint8_t             *out);
size_t fmessage__pack_to_buffer
                     (const FMessage   *message,
                      ProtobufCBuffer     *buffer);
FMessage *
       fmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fmessage__free_unpacked
                     (FMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Submessage_Closure)
                 (const Submessage *message,
                  void *closure_data);
typedef void (*FMessage_Closure)
                 (const FMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor submessage__descriptor;
extern const ProtobufCMessageDescriptor fmessage__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_fmessage_2eproto__INCLUDED */
