# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: array.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='array.proto',
  package='tutorial',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x61rray.proto\x12\x08tutorial\"#\n\x05\x65ntry\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x05\"<\n\x05myset\x12\x11\n\ttimestamp\x18\x01 \x02(\x05\x12 \n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x0f.tutorial.entry\"&\n\x05\x61rray\x12\x1d\n\x04sets\x18\x01 \x03(\x0b\x32\x0f.tutorial.myset')
)




_ENTRY = _descriptor.Descriptor(
  name='entry',
  full_name='tutorial.entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tutorial.entry.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='tutorial.entry.value', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=60,
)


_MYSET = _descriptor.Descriptor(
  name='myset',
  full_name='tutorial.myset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='tutorial.myset.timestamp', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entries', full_name='tutorial.myset.entries', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=122,
)


_ARRAY = _descriptor.Descriptor(
  name='array',
  full_name='tutorial.array',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sets', full_name='tutorial.array.sets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=162,
)

_MYSET.fields_by_name['entries'].message_type = _ENTRY
_ARRAY.fields_by_name['sets'].message_type = _MYSET
DESCRIPTOR.message_types_by_name['entry'] = _ENTRY
DESCRIPTOR.message_types_by_name['myset'] = _MYSET
DESCRIPTOR.message_types_by_name['array'] = _ARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

entry = _reflection.GeneratedProtocolMessageType('entry', (_message.Message,), dict(
  DESCRIPTOR = _ENTRY,
  __module__ = 'array_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.entry)
  ))
_sym_db.RegisterMessage(entry)

myset = _reflection.GeneratedProtocolMessageType('myset', (_message.Message,), dict(
  DESCRIPTOR = _MYSET,
  __module__ = 'array_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.myset)
  ))
_sym_db.RegisterMessage(myset)

array = _reflection.GeneratedProtocolMessageType('array', (_message.Message,), dict(
  DESCRIPTOR = _ARRAY,
  __module__ = 'array_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.array)
  ))
_sym_db.RegisterMessage(array)


# @@protoc_insertion_point(module_scope)
